import { useCallback, useEffect, useState } from 'react';
import { Bell, CalendarClock, CheckCircle2, Play, RotateCcw, Save, Send } from 'lucide-react';
import * as API from '../wailsjs/go/main/App';
import { main } from '../wailsjs/go/models';

const notificationEvents = [['start','启动'],['stop','停止'],['crash','崩溃'],['backup','备份'],['update','更新'],['player-join','玩家加入'],['player-leave','玩家离开'],['guardian','Guardian']] as const;

export default function EventsView({ id, run }: { id: string; run: Function }) {
  const [presets, setPresets] = useState<main.GamePreset[]>([]); const [events, setEvents] = useState<main.GamePreset[]>([]); const [active, setActive] = useState<main.ActiveGameEvent | null>(null); const [duration, setDuration] = useState(120);
  const [discord, setDiscord] = useState(new main.DiscordWebhookSettings({ serverId: id, enabled: false, configured: false, events: [] })); const [webhook, setWebhook] = useState('');
  const refresh = useCallback(async () => { setPresets(await API.ListGamePresets()); setEvents(await API.ListGameEvents()); const current = await API.GetActiveGameEvent(id); setActive(current?.serverId ? current : null); setDiscord(await API.GetDiscordWebhookSettings(id)); }, [id]);
  useEffect(() => { refresh(); }, [refresh]);
  const toggleEvent = (value: string) => { const selected = discord.events || []; setDiscord(new main.DiscordWebhookSettings({ ...discord, events: selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value] })); };
  return <div className="stack"><section className="panel"><div className="panel-heading"><div><h2>难度预设</h2><p>应用时自动处理运行状态并只覆盖相关字段</p></div><CalendarClock size={18}/></div><div className="preset-grid">{presets.map((preset) => <button key={preset.id} onClick={() => confirm(`应用“${preset.name}”预设？`) && run('preset', () => API.ApplyGamePreset(id, preset.id), '难度预设已应用')}><strong>{preset.name}</strong><span>{preset.description}</span></button>)}</div></section>
    <section className="panel"><div className="panel-heading"><div><h2>限时活动</h2><p>到期后自动恢复完整原始配置</p></div>{active && <button className="ghost" onClick={() => run('stop-event', async () => { await API.StopGameEvent(id); await refresh(); }, '活动已结束并恢复配置')}><RotateCcw size={14}/>立即恢复</button>}</div>{active ? <div className="active-event"><CheckCircle2 size={20}/><div><strong>{active.name}</strong><span>结束时间 {new Date(active.endsAt).toLocaleString()}</span></div></div> : <><div className="duration-row"><label>持续分钟<input type="number" min="1" value={duration} onChange={(e) => setDuration(Number(e.target.value))}/></label></div><div className="preset-grid">{events.map((event) => <button key={event.id} onClick={() => run('start-event', async () => { await API.StartGameEvent(id, event.id, duration, {}); await refresh(); }, '限时活动已开始')}><Play size={15}/><strong>{event.name}</strong><span>{event.description}</span></button>)}</div></>}</section>
    <section className="panel"><div className="panel-heading"><div><h2>Discord 通知</h2><p>Webhook 使用当前 Windows 用户的 DPAPI 加密</p></div><Bell size={18}/></div><div className="discord-form"><label><span>Webhook URL</span><input type="password" value={webhook} onChange={(e) => setWebhook(e.target.value)} placeholder={discord.configured ? '已配置，留空保持不变' : 'https://discord.com/api/webhooks/...'}/></label><label className="check-line"><input type="checkbox" checked={discord.enabled} onChange={(e) => setDiscord(new main.DiscordWebhookSettings({ ...discord, enabled: e.target.checked }))}/><span>启用通知</span></label><div className="event-checks">{notificationEvents.map(([value,label]) => <label key={value}><input type="checkbox" checked={(discord.events || []).includes(value)} onChange={() => toggleEvent(value)}/><span>{label}</span></label>)}</div><div className="modal-actions embedded-actions"><button className="ghost" onClick={() => run('test-discord', () => API.TestDiscordWebhook(id), '测试通知已发送')}><Send size={14}/>测试</button><button className="primary" onClick={() => run('save-discord', async () => { await API.SaveDiscordWebhook(id, webhook, discord.enabled, discord.events || []); setWebhook(''); await refresh(); }, 'Discord 通知已保存')}><Save size={14}/>保存</button></div></div></section>
  </div>;
}
