// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Announce(arg1:string,arg2:string):Promise<void>;

export function ApplyGamePreset(arg1:string,arg2:string):Promise<void>;

export function ApplyLauncherUpdate():Promise<void>;

export function ApplyOfficialPvPPreset(arg1:string):Promise<void>;

export function BanHistoricalPlayer(arg1:string,arg2:string):Promise<void>;

export function CheckExtensionUpdates(arg1:string):Promise<Array<main.ExtensionStatus>>;

export function CheckLauncherUpdate():Promise<main.LauncherUpdateInfo>;

export function CheckServerModUpdates(arg1:string):Promise<Array<main.ServerModCatalogEntry>>;

export function ChooseDirectory():Promise<string>;

export function ChooseFiles(arg1:string):Promise<Array<string>>;

export function ClearSteamCMDCache():Promise<void>;

export function CreateBackup(arg1:string):Promise<main.BackupEntry>;

export function CreateDiagnosticBundle(arg1:string):Promise<string>;

export function DeleteInstance(arg1:string,arg2:boolean):Promise<void>;

export function DeleteMaintenanceTask(arg1:string):Promise<void>;

export function DeleteMod(arg1:string,arg2:string):Promise<void>;

export function DeleteOfficialWorkshopMod(arg1:string,arg2:string):Promise<void>;

export function DuplicateInstance(arg1:string):Promise<main.ServerInstance>;

export function ExportClientMods(arg1:string):Promise<string>;

export function ForceStopServer(arg1:string):Promise<void>;

export function GetActiveGameEvent(arg1:string):Promise<main.ActiveGameEvent>;

export function GetAgentPreflight():Promise<main.AgentPreflightReport>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConsoleLog(arg1:string,arg2:number):Promise<string>;

export function GetDiscordWebhookSettings(arg1:string):Promise<main.DiscordWebhookSettings>;

export function GetFrpLog(arg1:string,arg2:number):Promise<string>;

export function GetFrpSettings(arg1:string):Promise<main.FrpSettings>;

export function GetFrpStatus(arg1:string):Promise<main.FrpStatus>;

export function GetHostResources():Promise<main.HostResources>;

export function GetLauncherVersion():Promise<string>;

export function GetOfficialWorkshopRoot(arg1:string):Promise<string>;

export function GetPerformanceAdvice(arg1:string):Promise<Array<main.PerformanceAdvice>>;

export function GetPlayers(arg1:string):Promise<Array<main.Player>>;

export function GetPluginCompatibility(arg1:string):Promise<main.PluginCompatibilityReport>;

export function GetSafeModeStatus(arg1:string):Promise<main.SafeModeStatus>;

export function GetSaveInspectorStatus():Promise<main.SaveInspectorStatus>;

export function GetServerCapabilities(arg1:string):Promise<main.ServerCapabilityReport>;

export function GetServerInfo(arg1:string):Promise<main.ServerInfo>;

export function GetServerMetrics(arg1:string):Promise<main.ServerMetrics>;

export function GetServerPaths(arg1:string):Promise<Record<string, string>>;

export function GetServerSettings(arg1:string):Promise<main.ServerSettings>;

export function GetServerSize(arg1:string):Promise<number>;

export function GetServerUpdateStatus(arg1:string):Promise<main.ServerUpdateStatus>;

export function GetSetupEnvironment(arg1:string):Promise<main.SetupEnvironment>;

export function GetStatus(arg1:string):Promise<main.RuntimeStatus>;

export function GetWorldSettingsValues(arg1:string):Promise<Record<string, string>>;

export function GetWorldSnapshot(arg1:string):Promise<main.WorldSnapshot>;

export function ImportExistingServer(arg1:string):Promise<main.ServerInstance>;

export function ImportMods(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ImportOfficialWorkshopMod(arg1:string,arg2:string):Promise<void>;

export function ImportUploadedServer(arg1:string,arg2:string):Promise<main.ServerImportResult>;

export function InspectSave(arg1:string):Promise<main.SaveInspectionResult>;

export function InstallFrp():Promise<main.FrpStatus>;

export function InstallOrUpdateServer(arg1:string):Promise<void>;

export function InstallSaveInspector():Promise<main.SaveInspectorStatus>;

export function InstallServerModArchive(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListAgentAudit(arg1:number):Promise<Array<main.AgentAuditEntry>>;

export function ListBackups(arg1:string):Promise<Array<main.BackupEntry>>;

export function ListBans(arg1:string):Promise<Array<string>>;

export function ListExtensions(arg1:string):Promise<Array<main.ExtensionStatus>>;

export function ListGameEvents():Promise<Array<main.GamePreset>>;

export function ListGamePresets():Promise<Array<main.GamePreset>>;

export function ListMaintenanceTasks(arg1:string):Promise<Array<main.MaintenanceTask>>;

export function ListMods(arg1:string):Promise<Array<main.ModEntry>>;

export function ListOfficialBackups(arg1:string):Promise<Array<main.BackupEntry>>;

export function ListOfficialWorkshopMods(arg1:string):Promise<Array<main.OfficialWorkshopMod>>;

export function ListPlayerHistory(arg1:string):Promise<Array<main.PlayerHistoryEntry>>;

export function ListServerModCatalog(arg1:string):Promise<Array<main.ServerModCatalogEntry>>;

export function OpenNexusModPage(arg1:string):Promise<void>;

export function OpenOfficialBackup(arg1:string,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenServerPath(arg1:string,arg2:string):Promise<void>;

export function PerformManagedUpdate(arg1:string,arg2:boolean):Promise<void>;

export function PlayerAction(arg1:string,arg2:main.ActionRequest):Promise<string>;

export function PruneBackups(arg1:string):Promise<void>;

export function QuickSetup(arg1:string,arg2:string):Promise<main.ServerInstance>;

export function ReadWorldSettings(arg1:string):Promise<string>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function RestorePluginsAfterSafeMode(arg1:string):Promise<void>;

export function RunDiagnostics(arg1:string):Promise<Array<main.DiagnosticResult>>;

export function RunMaintenanceTask(arg1:string):Promise<void>;

export function SaveDiscordWebhook(arg1:string,arg2:string,arg3:boolean,arg4:Array<string>):Promise<main.DiscordWebhookSettings>;

export function SaveFrpSettings(arg1:main.FrpSettings,arg2:string):Promise<main.FrpSettings>;

export function SaveInstance(arg1:main.ServerInstance):Promise<main.ServerInstance>;

export function SaveMaintenanceTask(arg1:main.MaintenanceTask):Promise<main.MaintenanceTask>;

export function SaveOfficialWorkshopRoot(arg1:string,arg2:string):Promise<void>;

export function SaveWorld(arg1:string):Promise<void>;

export function SaveWorldSettingsValues(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SelectInstance(arg1:string):Promise<void>;

export function SendRCON(arg1:string,arg2:string):Promise<string>;

export function SetOfficialWorkshopModEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetPlayerNote(arg1:string,arg2:string,arg3:string):Promise<main.PlayerHistoryEntry>;

export function SetPlayerWhitelist(arg1:string,arg2:string,arg3:boolean):Promise<main.PlayerHistoryEntry>;

export function ShutdownServer(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StartFrp(arg1:string):Promise<void>;

export function StartGameEvent(arg1:string,arg2:string,arg3:number,arg4:Record<string, string>):Promise<main.ActiveGameEvent>;

export function StartServer(arg1:string):Promise<void>;

export function StartServerSafeMode(arg1:string):Promise<void>;

export function StopFrp(arg1:string):Promise<void>;

export function StopGameEvent(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function TestDiscordWebhook(arg1:string):Promise<void>;

export function ToggleExtension(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleMod(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UnbanPlayer(arg1:string,arg2:string):Promise<void>;

export function UninstallServerMod(arg1:string,arg2:string):Promise<void>;

export function UpdateAllExtensions(arg1:string):Promise<Array<main.ExtensionUpdateResult>>;

export function UpdateExtension(arg1:string,arg2:string):Promise<main.ExtensionUpdateResult>;

export function WriteWorldSettings(arg1:string,arg2:string):Promise<void>;
