// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Announce(arg1, arg2) {
  return window['go']['main']['App']['Announce'](arg1, arg2);
}

export function ApplyGamePreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyGamePreset'](arg1, arg2);
}

export function ApplyLauncherUpdate() {
  return window['go']['main']['App']['ApplyLauncherUpdate']();
}

export function ApplyOfficialPvPPreset(arg1) {
  return window['go']['main']['App']['ApplyOfficialPvPPreset'](arg1);
}

export function BanHistoricalPlayer(arg1, arg2) {
  return window['go']['main']['App']['BanHistoricalPlayer'](arg1, arg2);
}

export function CheckExtensionUpdates(arg1) {
  return window['go']['main']['App']['CheckExtensionUpdates'](arg1);
}

export function CheckLauncherUpdate() {
  return window['go']['main']['App']['CheckLauncherUpdate']();
}

export function CheckServerModUpdates(arg1) {
  return window['go']['main']['App']['CheckServerModUpdates'](arg1);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ChooseFiles(arg1) {
  return window['go']['main']['App']['ChooseFiles'](arg1);
}

export function ClearSteamCMDCache() {
  return window['go']['main']['App']['ClearSteamCMDCache']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateDiagnosticBundle(arg1) {
  return window['go']['main']['App']['CreateDiagnosticBundle'](arg1);
}

export function DeleteInstance(arg1, arg2) {
  return window['go']['main']['App']['DeleteInstance'](arg1, arg2);
}

export function DeleteMaintenanceTask(arg1) {
  return window['go']['main']['App']['DeleteMaintenanceTask'](arg1);
}

export function DeleteMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteMod'](arg1, arg2);
}

export function DeleteOfficialWorkshopMod(arg1, arg2) {
  return window['go']['main']['App']['DeleteOfficialWorkshopMod'](arg1, arg2);
}

export function DuplicateInstance(arg1) {
  return window['go']['main']['App']['DuplicateInstance'](arg1);
}

export function ExportClientMods(arg1) {
  return window['go']['main']['App']['ExportClientMods'](arg1);
}

export function ForceStopServer(arg1) {
  return window['go']['main']['App']['ForceStopServer'](arg1);
}

export function GetActiveGameEvent(arg1) {
  return window['go']['main']['App']['GetActiveGameEvent'](arg1);
}

export function GetAgentPreflight() {
  return window['go']['main']['App']['GetAgentPreflight']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConsoleLog(arg1, arg2) {
  return window['go']['main']['App']['GetConsoleLog'](arg1, arg2);
}

export function GetDiscordWebhookSettings(arg1) {
  return window['go']['main']['App']['GetDiscordWebhookSettings'](arg1);
}

export function GetFrpLog(arg1, arg2) {
  return window['go']['main']['App']['GetFrpLog'](arg1, arg2);
}

export function GetFrpSettings(arg1) {
  return window['go']['main']['App']['GetFrpSettings'](arg1);
}

export function GetFrpStatus(arg1) {
  return window['go']['main']['App']['GetFrpStatus'](arg1);
}

export function GetHostResources() {
  return window['go']['main']['App']['GetHostResources']();
}

export function GetLauncherVersion() {
  return window['go']['main']['App']['GetLauncherVersion']();
}

export function GetOfficialWorkshopRoot(arg1) {
  return window['go']['main']['App']['GetOfficialWorkshopRoot'](arg1);
}

export function GetPerformanceAdvice(arg1) {
  return window['go']['main']['App']['GetPerformanceAdvice'](arg1);
}

export function GetPlayers(arg1) {
  return window['go']['main']['App']['GetPlayers'](arg1);
}

export function GetPluginCompatibility(arg1) {
  return window['go']['main']['App']['GetPluginCompatibility'](arg1);
}

export function GetSafeModeStatus(arg1) {
  return window['go']['main']['App']['GetSafeModeStatus'](arg1);
}

export function GetSaveInspectorStatus() {
  return window['go']['main']['App']['GetSaveInspectorStatus']();
}

export function GetServerCapabilities(arg1) {
  return window['go']['main']['App']['GetServerCapabilities'](arg1);
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function GetServerMetrics(arg1) {
  return window['go']['main']['App']['GetServerMetrics'](arg1);
}

export function GetServerPaths(arg1) {
  return window['go']['main']['App']['GetServerPaths'](arg1);
}

export function GetServerSettings(arg1) {
  return window['go']['main']['App']['GetServerSettings'](arg1);
}

export function GetServerSize(arg1) {
  return window['go']['main']['App']['GetServerSize'](arg1);
}

export function GetServerUpdateStatus(arg1) {
  return window['go']['main']['App']['GetServerUpdateStatus'](arg1);
}

export function GetSetupEnvironment(arg1) {
  return window['go']['main']['App']['GetSetupEnvironment'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetWorldSettingsValues(arg1) {
  return window['go']['main']['App']['GetWorldSettingsValues'](arg1);
}

export function GetWorldSnapshot(arg1) {
  return window['go']['main']['App']['GetWorldSnapshot'](arg1);
}

export function ImportExistingServer(arg1) {
  return window['go']['main']['App']['ImportExistingServer'](arg1);
}

export function ImportMods(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportMods'](arg1, arg2, arg3);
}

export function ImportOfficialWorkshopMod(arg1, arg2) {
  return window['go']['main']['App']['ImportOfficialWorkshopMod'](arg1, arg2);
}

export function ImportUploadedServer(arg1, arg2) {
  return window['go']['main']['App']['ImportUploadedServer'](arg1, arg2);
}

export function InspectSave(arg1) {
  return window['go']['main']['App']['InspectSave'](arg1);
}

export function InstallFrp() {
  return window['go']['main']['App']['InstallFrp']();
}

export function InstallOrUpdateServer(arg1) {
  return window['go']['main']['App']['InstallOrUpdateServer'](arg1);
}

export function InstallSaveInspector() {
  return window['go']['main']['App']['InstallSaveInspector']();
}

export function InstallServerModArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallServerModArchive'](arg1, arg2, arg3);
}

export function ListAgentAudit(arg1) {
  return window['go']['main']['App']['ListAgentAudit'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListBans(arg1) {
  return window['go']['main']['App']['ListBans'](arg1);
}

export function ListExtensions(arg1) {
  return window['go']['main']['App']['ListExtensions'](arg1);
}

export function ListGameEvents() {
  return window['go']['main']['App']['ListGameEvents']();
}

export function ListGamePresets() {
  return window['go']['main']['App']['ListGamePresets']();
}

export function ListMaintenanceTasks(arg1) {
  return window['go']['main']['App']['ListMaintenanceTasks'](arg1);
}

export function ListMods(arg1) {
  return window['go']['main']['App']['ListMods'](arg1);
}

export function ListOfficialBackups(arg1) {
  return window['go']['main']['App']['ListOfficialBackups'](arg1);
}

export function ListOfficialWorkshopMods(arg1) {
  return window['go']['main']['App']['ListOfficialWorkshopMods'](arg1);
}

export function ListPlayerHistory(arg1) {
  return window['go']['main']['App']['ListPlayerHistory'](arg1);
}

export function ListServerModCatalog(arg1) {
  return window['go']['main']['App']['ListServerModCatalog'](arg1);
}

export function OpenNexusModPage(arg1) {
  return window['go']['main']['App']['OpenNexusModPage'](arg1);
}

export function OpenOfficialBackup(arg1, arg2) {
  return window['go']['main']['App']['OpenOfficialBackup'](arg1, arg2);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenServerPath(arg1, arg2) {
  return window['go']['main']['App']['OpenServerPath'](arg1, arg2);
}

export function PerformManagedUpdate(arg1, arg2) {
  return window['go']['main']['App']['PerformManagedUpdate'](arg1, arg2);
}

export function PlayerAction(arg1, arg2) {
  return window['go']['main']['App']['PlayerAction'](arg1, arg2);
}

export function PruneBackups(arg1) {
  return window['go']['main']['App']['PruneBackups'](arg1);
}

export function QuickSetup(arg1, arg2) {
  return window['go']['main']['App']['QuickSetup'](arg1, arg2);
}

export function ReadWorldSettings(arg1) {
  return window['go']['main']['App']['ReadWorldSettings'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RestorePluginsAfterSafeMode(arg1) {
  return window['go']['main']['App']['RestorePluginsAfterSafeMode'](arg1);
}

export function RunDiagnostics(arg1) {
  return window['go']['main']['App']['RunDiagnostics'](arg1);
}

export function RunMaintenanceTask(arg1) {
  return window['go']['main']['App']['RunMaintenanceTask'](arg1);
}

export function SaveDiscordWebhook(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveDiscordWebhook'](arg1, arg2, arg3, arg4);
}

export function SaveFrpSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveFrpSettings'](arg1, arg2);
}

export function SaveInstance(arg1) {
  return window['go']['main']['App']['SaveInstance'](arg1);
}

export function SaveMaintenanceTask(arg1) {
  return window['go']['main']['App']['SaveMaintenanceTask'](arg1);
}

export function SaveOfficialWorkshopRoot(arg1, arg2) {
  return window['go']['main']['App']['SaveOfficialWorkshopRoot'](arg1, arg2);
}

export function SaveWorld(arg1) {
  return window['go']['main']['App']['SaveWorld'](arg1);
}

export function SaveWorldSettingsValues(arg1, arg2) {
  return window['go']['main']['App']['SaveWorldSettingsValues'](arg1, arg2);
}

export function SelectInstance(arg1) {
  return window['go']['main']['App']['SelectInstance'](arg1);
}

export function SendRCON(arg1, arg2) {
  return window['go']['main']['App']['SendRCON'](arg1, arg2);
}

export function SetOfficialWorkshopModEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOfficialWorkshopModEnabled'](arg1, arg2, arg3);
}

export function SetPlayerNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPlayerNote'](arg1, arg2, arg3);
}

export function SetPlayerWhitelist(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPlayerWhitelist'](arg1, arg2, arg3);
}

export function ShutdownServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShutdownServer'](arg1, arg2, arg3);
}

export function StartFrp(arg1) {
  return window['go']['main']['App']['StartFrp'](arg1);
}

export function StartGameEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartGameEvent'](arg1, arg2, arg3, arg4);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StartServerSafeMode(arg1) {
  return window['go']['main']['App']['StartServerSafeMode'](arg1);
}

export function StopFrp(arg1) {
  return window['go']['main']['App']['StopFrp'](arg1);
}

export function StopGameEvent(arg1) {
  return window['go']['main']['App']['StopGameEvent'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function TestDiscordWebhook(arg1) {
  return window['go']['main']['App']['TestDiscordWebhook'](arg1);
}

export function ToggleExtension(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleExtension'](arg1, arg2, arg3);
}

export function ToggleMod(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleMod'](arg1, arg2, arg3);
}

export function UnbanPlayer(arg1, arg2) {
  return window['go']['main']['App']['UnbanPlayer'](arg1, arg2);
}

export function UninstallServerMod(arg1, arg2) {
  return window['go']['main']['App']['UninstallServerMod'](arg1, arg2);
}

export function UpdateAllExtensions(arg1) {
  return window['go']['main']['App']['UpdateAllExtensions'](arg1);
}

export function UpdateExtension(arg1, arg2) {
  return window['go']['main']['App']['UpdateExtension'](arg1, arg2);
}

export function WriteWorldSettings(arg1, arg2) {
  return window['go']['main']['App']['WriteWorldSettings'](arg1, arg2);
}
